Easier adding cameras
BehrozRazaq/Refactoring_Home_assistant pull request #12
Opened 2023-12-11 20:34 UTC by Sebulon

Add improvement. Still contains some bug when restarting homeassistant, but otherwise good.

2023-12-11 21:36 UTC, BehrozRazaq requested changes
Gör om gör rätt :(

2023-12-11 21:36 UTC, BehrozRazaq commented
-2

2023-12-11 22:11 UTC, Oscar-Forsyth commented on homeassistant/components/trafikverket_camera/home_assistant.db
remove this file

2023-12-11 22:13 UTC, Oscar-Forsyth commented on homeassistant/components/trafikverket_camera/traffic_data_operations.py
bror... vi har också ändrat databas filen....
du måste säga till eller nåt för nu kommer vi ha merge conflicts

2023-12-11 22:18 UTC, Oscar-Forsyth commented on homeassistant/components/trafikverket_camera/coordinator.py
Samma sak här, kommer finnas merge conflicts

2023-12-11 22:18 UTC, Oscar-Forsyth commented on homeassistant/components/trafikverket_camera/statistics.py
och här

2023-12-11 22:20 UTC, Oscar-Forsyth requested changes
Så länge vi löser merge conflicts så borde det gå bra.
Men vi måste merga test_branch först tror jag

2023-12-13 13:47 UTC, OneZeroWasTaken approved these changes
As discussed in the meeting, this is approved

2023-12-13 13:47 UTC, merged