Joels arbete
BehrozRazaq/Refactoring_Home_assistant pull request #2
Opened 2023-10-09 15:14 UTC by frixxo

2023-10-10 07:23 UTC, frixxo commented on homeassistant/components/huawei_lte/notify.py
this is wrong

2023-10-11 14:14 UTC, OneZeroWasTaken requested changes
Good but fix/give feedback on the comments

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/huawei_lte/device_tracker.py
> +    tracked = _initialize_tracked_entites()
Missing arguments

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/huawei_lte/notify.py
yes it is

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/huawei_lte/notify.py
Please fix before we can accept your pr

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/isy994/helpers.py
> +            return _check_node_type(isy_data, device_type, platform, subnode_id, node)
It's a bit weird that _check_node_type always returns true which is returned here on this line. Just letting _check_node_type return void/None and having the call to it followed by return True would have made more sense.

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/isy994/select.py
> +        )  # aomehow this was not seen as a list of strings.
aomehow :D

2023-10-11 14:14 UTC, OneZeroWasTaken commented on homeassistant/components/isy994/services.py
> +async def async_setup_services(hass: HomeAssistant) -> None:
Why was async added? Do you know this won't introduce race conditions?

2023-10-12 08:19 UTC, OneZeroWasTaken requested changes
2 small fixes, then it can be merged

2023-10-12 08:19 UTC, OneZeroWasTaken commented on homeassistant/components/isy994/helpers.py
>              return _check_node_type(isy_data, device_type, platform, subnode_id, node)
This return has to go, otherwise it's good

2023-10-12 08:19 UTC, OneZeroWasTaken commented on homeassistant/components/huawei_lte/device_tracker.py
> +    tracked = _initialize_tracked_entites(hass, config_entry, async_add_entities, router, hosts)
Spelling mistake in function name here: "entites" should be "entities"

2023-10-12 09:56 UTC, merged