Erik
BehrozRazaq/Refactoring_Home_assistant pull request #4
Opened 2023-10-10 08:45 UTC by OneZeroWasTaken

2023-10-10 11:03 UTC, Sebulon requested changes
Fix the two comments, and then this is good for merging

2023-10-10 11:03 UTC, Sebulon commented on homeassistant/components/plex/__init__.py
> +        elif msgtype == "status":
Should lower the cognitive complexity by inverting the if statements, I calculated to 19 in cognitive complexity

2023-10-10 11:03 UTC, Sebulon commented on homeassistant/components/plex/__init__.py
> +def setup_websocket(hass, entry, plex_server, server_config, server_id):
No underscore... Not following convention

2023-10-11 12:29 UTC, OneZeroWasTaken commented on homeassistant/components/plex/__init__.py
> +        elif msgtype == "status":
Done

2023-10-11 12:29 UTC, OneZeroWasTaken commented on homeassistant/components/plex/__init__.py
> +def setup_websocket(hass, entry, plex_server, server_config, server_id):
Done

2023-10-11 12:37 UTC, OneZeroWasTaken reviewed
I don't understand how pr's work. Do I have to review my changes in order to show that I resolved the comments? ¯\_(ツ)_/¯

2023-10-11 12:38 UTC, OneZeroWasTaken commented
How do I remove "Changes requested" please remove it someone who knows thanks

2023-10-11 12:49 UTC, Sebulon approved these changes

2023-10-11 14:38 UTC, merged